### PR TITLE
Serialize focus and gridgen

### PR DESCRIPTION
**Pull request by ricaenriquez**
This addresses issues #41 and #42 .

### CODE REVIEW

**Comment by phobson** [comment]
Hey @ricaenriquez 

Thanks for pulling this together. Rather than creating a new copy of grid.py in the top-level directory, could you instead modify the existing pygridgen/grid.py file? Also, could you include your tests from the your email in pygridgen/tests/test_grid.py?

**Comment by ricaenriquez** [comment]
Yup - sorry about all these issues.I autoformatted the 3 changed files for
PEP8 and pushed the commits.

**Comment by phobson** [comment]
Looks like you've got some undefined variables in your tests:
https://travis-ci.org/pygridgen/pygridgen/jobs/454650135#L1062

Also, the auto PEP8 formatter altered a lot of lines that are not a part of this PR. Can we roll back commit and fix just the style issues in the PR? There were <10, IIRC, and they were mostly related to e.g., spaces after commas?

Are you able to run the tests locally? Do you currently have an environment on your machine that you use for grid generation?

**Comment by ricaenriquez** [comment]
Hey Paul - my bad - I tested the tests in a notebook where x,y, and beta
were defined.

I made a cleaner branch since there were annoying. I now see where the
tests fail notes are located. I'll keep an eye on this and make the
necessary changes.

I do have a grid generation environment (attached).

**Comment by phobson** [comment]
Closing in favor of #47

**Pull request closed without merging**
